version: '3.9'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://service-config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://service-eureka:8761/eureka/
      JAVA_OPTS: -Xmx512m -Xms256m
    networks:
      - bootcamp-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bootcamp-network:
    name: bootcamp-network
    external: true
