version: '3.9'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:}
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka:8761/eureka/
      JAVA_OPTS: -Xmx512m -Xms256m
    depends_on:
      - config-server
      - eureka
    networks:
      - bootcamp-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  config-server:
    image: service-config-server:latest
    container_name: service-config-server
    ports:
      - "8888:8888"
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - bootcamp-network
    restart: unless-stopped

  eureka:
    image: service-eureka:latest
    container_name: service-eureka
    ports:
      - "8761:8761"
    networks:
      - bootcamp-network
    restart: unless-stopped

networks:
  bootcamp-network:
    driver: bridge
